"""initial schema

Revision ID: eacfe913b084
Revises: 
Create Date: 2026-08-18 14:13:01.608670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacfe913b084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    op.drop_table('customers')
    op.drop_table('patients')
    op.drop_table('suppliers')
    op.drop_index(op.f('idx_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('carts')
    op.drop_table('order_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('idx_prescriptions_patient'), table_name='prescriptions')
    op.drop_index(op.f('idx_prescriptions_status'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_table('cart_items')
    op.drop_index(op.f('idx_drugs_code'), table_name='drugs')
    op.drop_index(op.f('idx_drugs_expiry'), table_name='drugs')
    op.drop_index(op.f('idx_drugs_stock'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_table('users')
    op.drop_index(op.f('idx_blockchain_record'), table_name='blockchain_records')
    op.drop_table('blockchain_records')
    op.drop_index(op.f('idx_audit_table'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('vendors')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('order_number', sa.TEXT(), nullable=True),
    sa.Column('subtotal', sa.REAL(), nullable=True),
    sa.Column('vat', sa.REAL(), nullable=True),
    sa.Column('discount', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('grand_total', sa.REAL(), nullable=True),
    sa.Column('payment_method', sa.TEXT(), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('business_name', sa.TEXT(), nullable=True),
    sa.Column('business_address', sa.TEXT(), nullable=True),
    sa.Column('business_phone', sa.TEXT(), nullable=True),
    sa.Column('business_email', sa.TEXT(), nullable=True),
    sa.Column('pan_number', sa.TEXT(), nullable=True),
    sa.Column('is_verified', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('rating', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('table_name', sa.TEXT(), nullable=True),
    sa.Column('record_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.TEXT(), nullable=False),
    sa.Column('old_values', sa.TEXT(), nullable=True),
    sa.Column('new_values', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.TEXT(), nullable=True),
    sa.Column('performed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_audit_table'), 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('blockchain_records',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tx_type', sa.TEXT(), nullable=False),
    sa.Column('record_id', sa.TEXT(), nullable=False),
    sa.Column('data_hash', sa.TEXT(), nullable=False),
    sa.Column('block_index', sa.INTEGER(), nullable=True),
    sa.Column('block_hash', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.TEXT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_blockchain_record'), 'blockchain_records', ['record_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("role IN ('admin','pharmacist','technician','cashier')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('drugs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('drug_code', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('generic_name', sa.TEXT(), nullable=True),
    sa.Column('manufacturer', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'Tablet'"), nullable=True),
    sa.Column('batch_number', sa.TEXT(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('unit_price', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('reorder_level', sa.INTEGER(), server_default=sa.text('(10)'), nullable=True),
    sa.Column('is_controlled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('discount_percent', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('rating', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint('stock_quantity >= 0'),
    sa.CheckConstraint('unit_price >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_code')
    )
    op.create_index(op.f('idx_drugs_stock'), 'drugs', ['stock_quantity'], unique=False)
    op.create_index(op.f('idx_drugs_expiry'), 'drugs', ['expiry_date'], unique=False)
    op.create_index(op.f('idx_drugs_code'), 'drugs', ['drug_code'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.Column('drug_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('rx_code', sa.TEXT(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_name', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('total_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('dispensed_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("status IN ('pending','dispensed','cancelled')"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rx_code')
    )
    op.create_index(op.f('idx_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_index(op.f('idx_prescriptions_patient'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), nullable=False),
    sa.Column('drug_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.REAL(), nullable=False),
    sa.Column('total_price', sa.REAL(), nullable=False),
    sa.Column('dosage', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.TEXT(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('drug_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sale_code', sa.TEXT(), nullable=False),
    sa.Column('sale_type', sa.TEXT(), server_default=sa.text("'OTC'"), nullable=True),
    sa.Column('total_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('payment_method', sa.TEXT(), server_default=sa.text("'Cash'"), nullable=True),
    sa.Column('discount_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('tax_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('final_amount', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("sale_type IN ('OTC','PRESCRIPTION','INSURANCE')"),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_code')
    )
    op.create_index(op.f('idx_sales_date'), 'sales', ['created_at'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('contact_person', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('patient_code', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_code')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('is_email_verified', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_2fa_enabled', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sale_id', sa.INTEGER(), nullable=False),
    sa.Column('drug_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.REAL(), nullable=False),
    sa.Column('total_price', sa.REAL(), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
